In [1]:
import os
import sys
sys.path.append(os.path.join(os.path.join(
    os.environ["RNB_PLANNING_DIR"], 'src')))
sys.path.append(os.path.join(
    os.environ["RNB_PLANNING_DIR"], 'src/scripts/demo_202107'))

CONNECT_INDY = False
CONNECT_MOBILE = False
USE_SDK = True

IP_CUR = "192.168.0.10"# get_ip_address()
MOBILE_IP = "192.168.0.102"
INDY_IP = "192.168.0.3"

print("Current PC IP: {}".format(IP_CUR))
print("Mobile ROB IP: {}".format(MOBILE_IP))

Current PC IP: 192.168.0.10
Mobile ROB IP: 192.168.0.102


In [2]:
INDY_BASE_OFFSET = (0.172,0,0.439)
INDY_BASE_RPY = (0,0,0)
TOOL_NAME = "brush_face"
WALL_THICKNESS = 0.01
CLEARANCE = 0.001
WS_HEIGHT = 1.6
COL_COLOR = (1,1,1,0.2)
    
# if EXP_SCENARIO == ExpType.REMOVE_OBS: ## Obstacle removing
#     BAG_COUNT = 5
#     CLOCK_COUNT = 0
#     TARGET_COUNT = 5
#     LOG_FORCE = False
# else: ## Contact 
#     BAG_COUNT = 3
#     CLOCK_COUNT = 3
#     TARGET_COUNT = 5
#     LOG_FORCE = True

from pkg.controller.combined_robot import *
from pkg.project_config import *

if not CONNECT_INDY:
    indy_7dof_client.kiro_tool.OFFLINE_MODE = True
kiro_udp_client.KIRO_UDP_OFFLINE_DEBUG = not CONNECT_MOBILE

mobile_config = RobotConfig(0, RobotType.kmb, ((0,0,0), (0,0,0)),
                "{}/{}".format(MOBILE_IP, IP_CUR))
robot_config = RobotConfig(1, RobotType.indy7, 
                           (INDY_BASE_OFFSET, INDY_BASE_RPY),
                INDY_IP, root_on="kmb0_platform", 
                           specs={"no_sdk":True} if not USE_SDK else {})

ROBOT_TYPE = robot_config.type
MOBILE_NAME = mobile_config.get_indexed_name()
ROBOT_NAME = robot_config.get_indexed_name()
crob = CombinedRobot(robots_on_scene=[mobile_config, robot_config]
              , connection_list=[True, CONNECT_INDY])

connection command:
kmb0: True
indy1: False


In [3]:
from util import *
from pkg.geometry.builder.scene_builder import SceneBuilder
from pkg.planning.scene import PlanningScene
from pkg.geometry.geometry import GeometryItem
from pkg.geometry.geotype import GEOTYPE

s_builder = SceneBuilder(None)
gscene = s_builder.create_gscene(crob)
gtems = s_builder.add_robot_geometries(
    color=COL_COLOR, display=True, collision=True)

gscene.set_workspace_boundary(
    -1, 4, -2.5, 2.5, -CLEARANCE, WS_HEIGHT, thickness=WALL_THICKNESS)

viewpoint = add_cam(gscene, tool_link="indy1_tcp")

Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
Please create a subscriber to the marker
publication OK
published: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Please create a subscriber to the marker


### MultiICP detector

In [4]:
from pkg.detector.multiICP.multiICP import MultiICP, MultiICP_Obj
from pkg.detector.multiICP.config import *
from pkg.detector.camera.realsense import RealSense
from pkg.detector.detector_interface import DetectionLevel

import open3d as o3d
import numpy as np

CONNECT_CAM = True

In [5]:
realsense = RealSense()

# from demo_utils.data_reconstructed_camera import DataRecontructedCamera
# dcam = DataRecontructedCamera(crob, viewpoint)
# if not CONNECT_CAM:
#     dcam.initialize()
    
if CONNECT_CAM:
    micp = MultiICP(realsense)
    micp.initialize()
#     dcam.ready_saving(*realsense.get_config())
#     cam_pose = viewpoint.get_tf(VIEW_POSE_EXT)
else:
    # use manually given camera configs
    config_list, img_dim = load_pickle(RNB_PLANNING_DIR+"release/multiICP_data/cam_configs.pkl")
    micp.initialize(config_list, img_dim)
    micp = MultiICP(dcam)
    micp.initialize()

Start streaming
Initialize Done


### Shared Detector

In [6]:
from pkg.detector.multiICP.shared_detector import SharedDetectorGen
sd = SharedDetectorGen(tuple(reversed(micp.dsize))+(3,))()
sd.init()

### set ICP config

In [7]:
# Load config file of object information
obj_info_dict = get_obj_info()

In [8]:
# initial guess는 실험하는거 보면서 수정?
micp_suitcase = MultiICP_Obj(obj_info_dict["suitcase"], None,
                        OffsetOnModelCoord("suitcase", R=Rot_axis(1, np.pi/2), offset=(0.,0.,0.)))


micp_clock = MultiICP_Obj(obj_info_dict["clock"], None,
                        OffsetOnModelCoord("clock", R=Rot_axis(1, np.pi/2), offset=(-0.07,0.03,0.)))


micp_table = MultiICP_Obj(obj_info_dict["dining table"], None,
                        OffsetOnModelCoord("dining table", R=np.identity(3), offset=(0.,0.,0.)))

In [9]:
micp_dict = {"suitcase": micp_suitcase, "clock": micp_clock, "dining table": micp_table}
# micp_dict = {"clock": micp_clock}
# micp_dict = {"dining table": micp_table}
# micp_dict = {"suitcase": micp_suitcase}

In [10]:
# set config information for micp
micp.set_config(micp_dict, sd, crob, viewpoint)

### Detect

In [12]:
pose_dict = micp.detect(visualize=True)

name_mask is None
clock not detected
dining table not detected
suitcase not detected


In [11]:
micp.set_ICP_thres(thres_ICP=0.1, thres_front_ICP=0.05)
pose_dict = micp.detect(name_mask=["clock"], visualize=True)

name_mask is ['clock']
===== Detected : clock, 2 object(s) =====

'clock' is not in gscene. Use manual input for initial guess

Apply point-to-point ICP
Total ICP Transformation is:
[[ 0.99904572  0.01233316  0.0418993  -0.19512462]
 [ 0.04254406 -0.05773461 -0.99742504  0.30709699]
 [-0.00988237  0.99825578 -0.05820422  0.76476385]
 [ 0.          0.          0.          1.        ]]
initial: 
[[ 1.    0.01  0.04 -0.2 ]
 [ 0.04 -0.06 -1.    0.31]
 [-0.01  1.   -0.06  0.76]
 [ 0.    0.    0.    1.  ]]
Apply point-to-point ICP
Total ICP Transformation is:
[[ 0.99794027 -0.00612218  0.06385712 -0.19631769]
 [ 0.06304802 -0.09010618 -0.99393452  0.30914297]
 [ 0.01183896  0.99591335 -0.0895346   0.76116971]
 [ 0.          0.          0.          1.        ]]
result: 
[[ 1.   -0.01  0.06 -0.2 ]
 [ 0.06 -0.09 -0.99  0.31]
 [ 0.01  1.   -0.09  0.76]
 [ 0.    0.    0.    1.  ]]
Found 6DoF pose of clock_1

'clock' is not in gscene. Use manual input for initial guess

Apply point-to-point ICP
To

In [ ]:
pose_dict = micp.detect(name_mask=["suitcase", "clock", "dining table"])

### Update Object to scene

In [ ]:
# add table
center, rpy = pose_refine("dining table", pose_dict["dining table"])
table_vis = add_table(gscene, "table", center, rpy)

In [ ]:
# add or update suitcase
add_update_object(gscene, crob, "suitcase", pose_dict, height = 0)

In [13]:
# add or update clock
add_update_object(gscene, crob, "clock", pose_dict, separate_dist=0.2, height = 0.734)

Total 0 clock in the scene
Add new clock in the scene
Add new clock in the scene


### Test code for multiple instance detection
* MultiICP Detector 이전까지 실행시키고 아래의 코드 실행
* Separte distance는 수동으로 조절

In [5]:
# Origianlly, 4 suitcases are existed in scene
c10 = add_carrier(gscene, "suitcase_0", (1.,1.,0), (0,0,0))
c11 = add_carrier(gscene, "suitcase_1", (1.,2.,0), (0,0,0))
c12 = add_carrier(gscene, "suitcase_2", (2.,1.,0), (0,0,0))
c13 = add_carrier(gscene, "suitcase_3", (2.,2.,0), (0,0,0))

In [6]:
# Detection result, but T1, T2 are already detected objects so, these are in the scene
# T3 is newly detected object so this is not in the scene
# Therefore, 1 and 2 should be updated, but 3 should be added

T1 = SE3(Rot_axis(3, np.pi/10), (1.1,1.18,0.3))
T2 = SE3(np.identity(3), (2.1,1.88,-0.1))
T3 = SE3(Rot_axis(1, -np.pi/5) , (3.1,1.9,-0.2))
pose_dict = {"suitcase_0":T1, "suitcase_1":T2, "suitcase_2":T3}

In [7]:
add_update_object(gscene, crob, "suitcase", pose_dict)

Total 4 suitcase in the scene
Update existing suitcase in the scene
Update existing suitcase in the scene
Add new suitcase in the scene
