In [1]:
import open3d as o3d
import numpy as np
import copy
from utils.pyransac3d import *

In [2]:
def extract_outliers(pcd_points, inliers):
    temp = []
    
    for i in range(len(pcd_points)):
        idx = i
        if not idx in inliers:
            temp.append(pcd_points[idx])
            
    p_outliers = np.zeros((len(temp), 3))
    for i in range(len(temp)):
        p_outliers[i] = temp[i]
    return p_outliers

In [3]:
pcd = o3d.io.read_point_cloud("krylon.pcd")

In [3]:
box = o3d.geometry.TriangleMesh.create_box(width = 0.3, height = 0.4, depth = 0.5)

In [63]:
R = box.get_rotation_matrix_from_xyz((np.pi / 2, 0, np.pi / 4))
R

array([[ 7.07106781e-01, -7.07106781e-01,  0.00000000e+00],
       [ 4.32978028e-17,  4.32978028e-17, -1.00000000e+00],
       [ 7.07106781e-01,  7.07106781e-01,  6.12323400e-17]])

In [64]:
box.rotate(R)

geometry::TriangleMesh with 8 points and 12 triangles.

In [4]:
pcd = box.sample_points_uniformly(number_of_points=5000)

In [5]:
o3d.visualization.draw_geometries([pcd])

In [66]:
points = np.asarray(pcd.points)

In [67]:
points.shape

(5000, 3)

In [68]:
geometry_list = [Cuboid(), Sphere(), Cylinder()]

In [76]:
eq, inliers = geometry_list[0].fit(points, thresh=0.005, maxIteration=2000)

len(inliers)

2563

In [11]:
eq

array([[ 7.07106781e-01, -4.77055387e-16, -7.07106781e-01,
        -1.29289322e-01],
       [ 7.07106781e-01, -8.47175031e-15,  7.07106781e-01,
        -4.32842712e-01],
       [ 6.32776119e-15,  1.00000000e+00,  5.65310299e-15,
        -4.50000000e-01]])

In [11]:
a = np.array([eq[0][0], eq[1][0], eq[2][0]])
a

array([ 7.07106781e-01, -8.84783293e-19, -7.07106781e-01])

In [ ]:
idx = a.argsort()[::-1]
idx

In [ ]:
inliers

In [13]:
outliers = extract_outliers(points, inliers)

In [14]:
pcd_outliers = o3d.geometry.PointCloud()

In [15]:
pcd_outliers.points = o3d.utility.Vector3dVector(outliers)

In [16]:
o3d.visualization.draw_geometries([pcd_outliers])

In [17]:
eq_, inliers_ = geometry_list[0].fit(outliers, thresh=0.005, maxIteration=700)

In [18]:
eq_

array([[ 7.07106781e-01,  2.45932992e-16, -7.07106781e-01,
        -1.29289322e-01],
       [ 7.07106781e-01,  2.99395578e-16,  7.07106781e-01,
        -4.32842712e-01],
       [ 3.85605529e-16, -1.00000000e+00,  3.78037571e-17,
         1.13734416e-01]])

In [ ]:
inliers_

In [ ]:
len(inliers_)

In [ ]:
center, radius, inliers = geometry_list[1].fit(points, thresh=0.005, maxIteration=1000)

len(inliers)

In [ ]:
center, axis, radius, inliers = geometry_list[2].fit(points, thresh=0.005, maxIteration=1000)

len(inliers)

In [26]:
a = np.identity(4)

In [31]:
b = np.array([np.mean(a[:,0]), np.mean(a[:,1]), np.mean(a[:,2]), np.mean(a[:,3])])

In [32]:
b

array([0.25, 0.25, 0.25, 0.25])