In [8]:
import pyransac3d as pyc
import open3d as o3d
import numpy as np
import copy

In [9]:
cyl = o3d.geometry.TriangleMesh.create_cylinder(radius=0.05, height=0.2)
R = cyl.get_rotation_matrix_from_xyz((np.pi / 3, -np.pi / 4, np.pi / 5))
cyl.rotate(R)
cyl.translate((-0.6,0.2,0.3))
pcd = cyl.sample_points_uniformly(8000)
pcd = pcd.uniform_down_sample(every_k_points=10)

In [10]:
pcd.estimate_normals()

In [12]:
point_normals = np.asarray(pcd.normals)

In [11]:
pcd.normalize_normals()

PointCloud with 800 points.

In [13]:
point_normals

array([[ 0.68294661,  0.60404525, -0.4107472 ],
       [ 0.69639724,  0.54523663, -0.46663466],
       [ 0.32540344,  0.60653627, -0.72541461],
       ...,
       [ 0.97786367,  0.15253668,  0.14323131],
       [ 0.76578236, -0.03265035,  0.64227046],
       [ 0.8791904 ,  0.19450704,  0.4349612 ]])

In [3]:
points = np.asarray(pcd.points)

In [18]:
cylinder = pyc.Cylinder()

In [29]:
center, axis, radius, inliers = cylinder.fit(points, thresh=0.01)

In [4]:
sphere = pyc.Sphere()

In [5]:
center, radius, inliers = sphere.fit(points, thresh=0.01)

In [30]:
center

array([-0.62325875,  0.16709968,  0.31497172])

In [31]:
axis

array([ 0.14086092,  0.96248906, -0.23189008])

In [32]:
radius

0.05319022232574944

In [33]:
len(inliers)

298

In [7]:
pcd_inliers = o3d.geometry.PointCloud()
p_inliers= []
for i in range(len(inliers)):
    p_inliers.append(points[inliers[i]])
pcd_inliers.points = o3d.utility.Vector3dVector(p_inliers)
pcd_inliers.paint_uniform_color((1,0,0))

PointCloud with 346 points.

In [8]:
pcd.paint_uniform_color((0,0,0))
o3d.visualization.draw_geometries([pcd,pcd_inliers])