In [1]:
from __future__ import print_function
from IPython.core.display import display, HTML

display(HTML("<style>.container { width:90% !important; } </style>"))
import matplotlib.pyplot as plt
from pkg.marker_config import *
from pkg.constraint_graph import *
from pkg.constraint.constraint_action import *
from pkg.constraint.constraint_object import *
from pkg.constants import *
from pkg.utils.plot_utils import *
from pkg.utils.utils import *
from pkg.environment_builder import *
from pkg.ui.ui_broker import *
from pkg.controller.combined_robot import *
from pkg.controller.combined_robot import CombinedRobot, XYZ_RPY_ROBOTS_DEFAULT
from pkg.data_collecting.sampling import *

VISUALIZE = True
graph = None
SAMPLED_DATA = defaultdict(dict)
UPDATE_DAT = True

GLOBAL_FILENAME = "global.json"
WORLD_FILENAME = "world.json"
SCENE_FILENAME = "scene.json"
DATA_PATH = "./data"
CONVERTED_PATH = "./data/converted"
try_mkdir(CONVERTED_PATH)

gtimer = GlobalTimer.instance()
elog = Logger()
crob = CombinedRobot(connection_list=(False, False))

CHECK_DICT = {}

# ## Load Global params
DATASET_LIST = sorted(filter(lambda x: x not in ["backup", "converted"], os.listdir(DATA_PATH)))

connection_list
(False, False)


## dataset

In [2]:
DATASET = DATASET_LIST[0]
CHECK_DICT[DATASET] = {}
CURRENT_PATH = os.path.join(DATA_PATH, DATASET)
try_mkdir(os.path.join(CONVERTED_PATH, DATASET))


## Load global params
GLOBAL_PARAMS = load_json(os.path.join(CURRENT_PATH, GLOBAL_FILENAME))
WDH = GLOBAL_PARAMS["WDH"]
L_CELL = GLOBAL_PARAMS["L_CELL"]
RATIO_DIMS = GLOBAL_PARAMS["RATIO_DIMS"]
REACH_OFFSET_DICT = GLOBAL_PARAMS["REACH_OFFSET_DICT"]
GRIPPER_REFS = GLOBAL_PARAMS["GRIPPER_REFS"]
BASE_LINK = GLOBAL_PARAMS["BASE_LINK"]
S_F_RATIO = GLOBAL_PARAMS["S_F_RATIO"]
TIMEOUT = GLOBAL_PARAMS["TIMEOUT"]

CENTER = tuple(np.divide(WDH, 2, dtype=np.float))
Ws, Ds, Hs = WDH
Nw, Nd, Nh = Nwdh = int(Ws / L_CELL), int(Ds / L_CELL), int(Hs / L_CELL)
L_MAX = L_CELL * RATIO_DIMS
print("scene size: {} ({},{},{})".format(Nw * Nd * Nh, Nw, Nd, Nh))


scene size: 3375 (15,15,15)


## world

In [3]:
#Iterate world
WORLD_LIST = sorted(filter(lambda x: not x.endswith(".json"), os.listdir(CURRENT_PATH)))

for WORLD in WORLD_LIST[:1]:
    CHECK_DICT[DATASET][WORLD] = {}
    WORLD_PATH = os.path.join(CURRENT_PATH, WORLD)
    try_mkdir(os.path.join(CONVERTED_PATH, DATASET, WORLD))
    SAMPLED_DATA["WORLD"] = load_json(os.path.join(WORLD_PATH, WORLD_FILENAME))
    Trbt_dict = SAMPLED_DATA["WORLD"]["Trbt_dict"]
    reach_center_dict = {k: tuple(np.add(v[0], REACH_OFFSET_DICT[k])) for k, v in Trbt_dict.items()}

    cam = None
    # set urdf
    xcustom, JOINT_NAMES, LINK_NAMES, urdf_content = set_custom_robots(crob.robots_on_scene, Trbt_dict,
                                                                       crob.custom_limits, start_rviz=VISUALIZE)
    ghnd = GeometryHandle(urdf_content)
    time.sleep(2)

    # set graph
    graph = ConstraintGraph(ghnd=ghnd, urdf_path=URDF_PATH, joint_names=JOINT_NAMES, link_names=LINK_NAMES,
                            urdf_content=urdf_content, combined_robot=crob)
    graph.set_camera(cam)
    graph.set_cam_robot_collision(_add_cam_poles=False, color=(1, 1, 0, 0.3))
    if VISUALIZE: graph.set_rviz()

    # start UI
    ui_broker = UIBroker.instance()
    ui_broker.initialize(graph)
    ui_broker.start_server()
    
    ui_broker.set_tables()

    for gripper in GRIPPER_REFS.values():
        graph.register_binder(name=gripper['bname'], _type=FramedTool, point=gripper['tcp_ref'], rpy=[0, 0, 0],
                              link_name=gripper['link_name'])
    graph.register_binder(name='base', _type=PlaceFrame, point=[0, 0, 0], rpy=[0, 0, 0], link_name=BASE_LINK)
    vtem = graph.ghnd.create_safe(name="virtual", gtype=GEOTYPE.SPHERE, link_name=BASE_LINK,
                                  dims=(0, 0, 0), center=(0, 0, 0), rpy=(0, 0, 0), collision=False, display=False
                                  )
    graph.add_object("virtual",
                     SingleHandleObject(_object=vtem,
                                        action_point=FramePoint(name="point", _object=vtem, point=(0, 0, 0),
                                                                rpy=(0, 0, 0), name_full=None)),
                     binding=("point", "base"))

    obj_list = []
    col_obj_list = []

    # Iterate scene
    SCENE_LIST = sorted(filter(lambda x: not x.endswith(".json"), os.listdir(WORLD_PATH)))
    for SCENE in SCENE_LIST:
        try_mkdir(os.path.join(CONVERTED_PATH, DATASET, WORLD, SCENE))
        CHECK_DICT[DATASET][WORLD][SCENE] = {}
        SCENE_PATH = os.path.join(WORLD_PATH, SCENE)
        SAMPLED_DATA["SCENE"] = load_json(os.path.join(SCENE_PATH, SCENE_FILENAME))
        Q_s = np.array(SAMPLED_DATA["SCENE"]["Q_s"])
        Q_s, links, link_verts, link_ctems, link_rads = sample_joint(graph, Q_s_loaded=Q_s)
        Q_s_dict = SAMPLED_DATA["SCENE"]["Q_s_dict"]
        obj_dat = SAMPLED_DATA["SCENE"]["obj_dat"]

        if VISUALIZE:
            graph.show_pose(Q_s)
            time.sleep(1)
            graph.show_pose(Q_s)
            time.sleep(1)
            graph.show_pose(Q_s)
        for obj in obj_list: graph.remove_geometry(obj)
        for odat in obj_dat:
            nbox, gtype, dims, color, center, rpy = odat["nbox"], getattr(GEOTYPE, odat["gtype"]), odat["dims"], \
                                                    odat["color"], odat["center"], odat["rpy"]
            obj = graph.ghnd.create_safe(
                name="{}_{}_{}_{}".format(gtype.name, *nbox), link_name=BASE_LINK, gtype=gtype,
                center=center, rpy=rpy, dims=dims, color=color, display=True, collision=True, fixed=True)
            obj_list.append(obj)
            graph.add_marker(obj, vis=VISUALIZE)

        for obj in col_obj_list: graph.remove_geometry(obj)

        if VISUALIZE: graph.set_rviz()

        # Iterate actions
        ACTION_LIST = sorted(filter(lambda x: x != SCENE_FILENAME, os.listdir(SCENE_PATH)))
        for ACTION in ACTION_LIST[:1]:
            N_action = get_action_count(CONVERTED_PATH, DATASET, WORLD, SCENE, ACTION)
            print("[BEGIN] {} - {} - {} - {} ===============".format(DATASET, WORLD, SCENE, ACTION))
            CHECK_DICT[DATASET][WORLD][SCENE][ACTION] = {}
            snode_dict = {int(k): v for k, v in load_json(os.path.join(SCENE_PATH, ACTION)).items()}
            snode_keys = sorted(snode_dict.keys())

            if snode_keys:
                sk0 = snode_keys[0]
                rname, tar, inhand_coll, obj_coll = \
                    snode_dict[sk0]["rname1"], snode_dict[sk0]["rname2"], \
                    snode_dict[sk0]["obj1"]["collision"], snode_dict[sk0]["obj2"]["collision"]
            else:
                print("[END] {} - {} - {} - {} ===============".format(DATASET, WORLD, SCENE, ACTION))
                print("No Item")


            if rname and tar:  # handover case
                action_type = "HANDOVER"
            elif inhand_coll:  # place case
                action_type = "PLACE"
            elif obj_coll:  # pick case
                action_type = "PICK"
            else:
                raise (RuntimeError("non-implemented case"))

            ID=None

            elog = Logger()
            acquired = False
            for i_act in range(N_action):
                scene_data, success, skey = load_scene_data(CONVERTED_PATH, DATASET, WORLD, SCENE, ACTION, i_act, crob.joint_num)
                print(success)
                try:
                    snode = snode_dict[skey]
                    rname, inhand, obj, tar, dims_bak, color_bak, succ, _ = load_manipulation_from_dict(snode,
                                                                                                        graph.ghnd)
                except Exception as e:
                    if not elog.log(str(e)):
                        break
                    continue
                try:

                    if rname and tar:  # handover case
                        remove_map = [[], [0, 1]]
                        action_type = "HANDOVER"
                    elif inhand.collision:  # place case
                        remove_map = [[], [0, 1]]
                        action_type = "PLACE"
                    elif obj.collision:  # pick case
                        remove_map = [[1], [0]]
                        action_type = "PICK"
                    else:
                        remove_map = [[], [0,1]]
                        action_type = "None"
                        raise (RuntimeError("non-implemented case"))
                    if VISUALIZE: show_manip_coords(graph, GRIPPER_REFS, action_type, rname, inhand, obj, rname2=tar)
                    raw_input("Press Enter to continue...")
                except Exception as e:
                    if not elog.log(str(e)):
                        break
                finally:
                    remove1 = [[inhand, obj][iii] for iii in remove_map[0]]
                    remove2 = [[inhand, obj][iii] for iii in remove_map[1]]
                    reset_rendering(graph, action_type, remove1, remove2, dims_bak, color_bak, sleep=True,
                                    vis=VISUALIZE)
            print("[END] {} - {} - {} - {} ===============".format(DATASET, WORLD, SCENE, ACTION))
        print("============================ TERMINATE {} ===================================".format(ID))

Unknown tag "hardwareInterface" in /robot[@name='custom_robots']/transmission[@name='indy0_tran0']/actuator[@name='indy0_motor0']
Unknown tag "hardwareInterface" in /robot[@name='custom_robots']/transmission[@name='indy0_tran1']/actuator[@name='indy0_motor1']
Unknown tag "hardwareInterface" in /robot[@name='custom_robots']/transmission[@name='indy0_tran2']/actuator[@name='indy0_motor2']
Unknown tag "hardwareInterface" in /robot[@name='custom_robots']/transmission[@name='indy0_tran3']/actuator[@name='indy0_motor3']
Unknown tag "hardwareInterface" in /robot[@name='custom_robots']/transmission[@name='indy0_tran4']/actuator[@name='indy0_motor4']
Unknown tag "hardwareInterface" in /robot[@name='custom_robots']/transmission[@name='indy0_tran5']/actuator[@name='indy0_motor5']


Please create a subscriber to the marker
publication OK
published: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Please create a subscriber to the marker
Dash is running on http://127.0.0.1:8050/

 * Serving Flask app "pkg.ui.dash_launcher" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off
[BEGIN] 20201208-121454 - WORLD-20201208-121454 - SCENE-20201208-121456 - 20201208-121507.json ===============
True
Press Enter to continue...
False
Press Enter to continue...
False
Press Enter to continue...
False
Press Enter to continue...
[END] 20201208-121454 - WORLD-20201208-121454 - SCENE-20201208-121456 - 20201208-121507.json ===============
============================ TERMINATE None ===================================


In [4]:
scene_pickle = load_pickle(os.path.join(CONVERTED_PATH, DATASET, WORLD, SCENE, "scene.pkl"))

In [5]:
scene_pickle

{'ctem_cells': defaultdict(list, {'BOX': array([[ 5,  5,  1],
                     [ 8,  2,  5],
                     [ 4,  4, 11],
                     [ 4,  2,  6],
                     [ 2,  0,  8],
                     [11, 12,  7],
                     [ 9,  7,  4],
                     [ 7, 11, 10],
                     [ 5, 14,  1],
                     [12, 13,  8],
                     [ 6, 12, 11],
                     [ 3, 14,  6],
                     [ 3, 13,  3],
                     [ 9, 12, 10],
                     [ 8,  3,  4],
                     [ 5,  8, 11],
                     [ 7,  4,  2],
                     [ 1, 12,  7],
                     [13, 13,  0],
                     [12,  9, 10],
                     [ 9,  6,  1],
                     [ 2,  3,  5],
                     [ 0,  2,  6],
                     [ 6,  6, 10],
                     [10, 12,  0],
                     [ 4,  1,  7],
                     [10,  7,  0],
                     [ 2,  1

In [9]:
joint_num = 13
N_vtx_box = 3*8
N_mask_box = 1
N_joint_box = joint_num
N_label_box = N_vtx_box+N_mask_box+N_joint_box
N_vtx_cyl = 3*2+1
N_mask_cyl = 1
N_joint_cyl = joint_num
N_label_cyl = N_vtx_cyl+N_mask_cyl+N_joint_cyl
N_vtx_init = 3*8
N_mask_init = 1
N_joint_init = joint_num
N_label_init = N_vtx_init+N_mask_init+N_joint_init
N_vtx_goal = 3*8
N_mask_goal = 1
N_joint_goal = joint_num
N_label_goal = N_vtx_goal+N_mask_goal+N_joint_goal
N_joint_label = 6*joint_num
N_cell_label = N_label_box+N_label_cyl+N_label_init+N_label_goal + N_joint_label
N_BEGIN_CYL = N_vtx_box+N_mask_box+N_joint_box
N_BEGIN_INIT = N_BEGIN_CYL+N_vtx_cyl+N_mask_cyl+N_joint_cyl
N_BEGIN_GOAL = N_BEGIN_INIT+N_vtx_init+N_mask_init+N_joint_init

In [10]:
np.where(scene_data[:,:,:,N_BEGIN_CYL+N_vtx_cyl])

(array([ 0,  0,  1,  1,  1,  1,  2,  2,  2,  2,  2,  3,  3,  3,  3,  4,  4,
         4,  4,  5,  5,  5,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,
         8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,
        10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 13, 13]),
 array([ 6, 12,  5,  6,  8, 11,  5,  6,  6,  7, 12,  3,  6,  7,  8,  5,  7,
         8, 13,  5,  6,  6,  7, 13,  8, 10, 11,  3,  8, 12, 12, 13, 13, 13,
         4,  8,  9,  9, 10, 10, 11, 11, 11, 12, 13, 13, 14, 14, 14, 11, 14,
         9, 10, 14,  6,  7,  9, 10, 14,  8, 11,  7, 10]),
 array([ 1,  5,  5,  6,  6,  8,  5,  0,  6,  2, 11,  1,  5,  4,  3,  2,  5,
         6,  9, 12,  8,  9,  7,  0,  8,  3,  9,  3,  9,  6,  7,  7,  8,  9,
         7,  7,  5,  6,  0,  3,  3,  4,  5,  6,  7,  8,  5,  8,  9,  1, 11,
         2,  0,  0,  6,  5,  1,  7,  2,  4,  0,  1,  5]))

In [11]:
np.where(scene_data[:,:,:,0+N_vtx_box])

(array([ 0,  1,  2,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5,  5,  6,  6,
         6,  7,  7,  7,  8,  8,  9,  9,  9, 10, 10, 11, 12, 12, 13]),
 array([ 2, 12,  0,  1,  3,  5,  5, 13, 14,  1,  2,  4,  5,  8, 14,  6, 11,
        12,  4, 11, 14,  2,  3,  6,  7, 12,  7, 12, 12,  9, 13, 13]),
 array([ 6,  7,  8,  4,  5,  6,  6,  3,  6,  7,  6, 11,  1, 11,  1, 10,  9,
        11,  2, 10,  9,  5,  4,  1,  4, 10,  0,  0,  7, 10,  8,  0]))

In [12]:
np.where(scene_data[:,:,:,N_BEGIN_INIT+N_vtx_box])

(array([7]), array([14]), array([9]))

In [13]:
np.where(scene_data[:,:,:,N_BEGIN_GOAL+N_vtx_box])

(array([3]), array([5]), array([7]))

In [15]:
scene_data[3,5,7,N_BEGIN_GOAL: N_BEGIN_GOAL+N_vtx_box]

array([-0.12327989,  0.01191176, -0.07427152, -0.0862594 ,  0.01727275,
       -0.10156834, -0.13930185, -0.05637197, -0.10941146, -0.10228136,
       -0.05101098, -0.13670828, -0.08076001, -0.02410126, -0.02367803,
       -0.04373953, -0.01874028, -0.05097485, -0.09678198, -0.09238499,
       -0.05881797, -0.05976149, -0.08702401, -0.08611479])

In [14]:
success

False

## initialize constants

In [ ]:
joint_num = crob.joint_num

N_vtx_box = 3*8
N_mask_box = 1
N_joint_box = joint_num
N_label_box = N_vtx_box+N_mask_box+N_joint_box
N_vtx_cyl = 3*2+1
N_mask_cyl = 1
N_joint_cyl = joint_num
N_label_cyl = N_vtx_cyl+N_mask_cyl+N_joint_cyl
N_vtx_init = 3*8
N_mask_init = 1
N_joint_init = joint_num
N_label_init = N_vtx_init+N_mask_init+N_joint_init
N_vtx_goal = 3*8
N_mask_goal = 1
N_joint_goal = joint_num
N_label_goal = N_vtx_goal+N_mask_goal+N_joint_goal
N_joint_label = 6*joint_num
N_cell_label = N_label_box+N_label_cyl+N_label_init+N_label_goal + N_joint_label
N_BEGIN_CYL = N_vtx_box+N_mask_box+N_joint_box
N_BEGIN_INIT = N_BEGIN_CYL+N_vtx_cyl+N_mask_cyl+N_joint_cyl
N_BEGIN_GOAL = N_BEGIN_INIT+N_vtx_init+N_mask_init+N_joint_init

## show all items

In [ ]:
centers = get_centers(Nwdh, L_CELL)
for idx, center, cell_dat in zip(range(Nwdh[0]*Nwdh[1]*Nwdh[2]), centers.reshape((-1,3)), scene_data.reshape((-1, scene_data.shape[-1]))):
    gtem, mask, chain = get_box_diplay(ghnd, "box_{}".format(idx), cell_dat, 0, joint_num, center)
    if mask:
        graph.add_marker(gtem)
    gtem, mask, chain = get_cyl_diplay(ghnd, "cyl_{}".format(idx), cell_dat, N_BEGIN_CYL, joint_num, center)
    if mask:
        graph.add_marker(gtem)
    gtem, mask, chain = get_box_diplay(ghnd, "init_{}".format(idx), cell_dat, N_BEGIN_INIT, joint_num, center, color=(0,0,0,0.8))
    if mask:
        graph.add_marker(gtem)
    gtem, mask, chain = get_box_diplay(ghnd, "goal_{}".format(idx), cell_dat, N_BEGIN_GOAL, joint_num, center, color=(0.8,0.8,0.8,0.8))
    if mask:
        graph.add_marker(gtem)

## remove all items

In [ ]:
centers = get_centers(Nwdh, L_CELL)
for idx, center, cell_dat in zip(range(Nwdh[0]*Nwdh[1]*Nwdh[2]), centers.reshape((-1,3)), scene_data.reshape((-1, scene_data.shape[-1]))):
    gtem, mask, chain = get_box_diplay(ghnd, "box_{}".format(idx), cell_dat, 0, joint_num, center)
    if mask:
        graph.remove_geometry(gtem)
    gtem, mask, chain = get_cyl_diplay(ghnd, "cyl_{}".format(idx), cell_dat, N_BEGIN_CYL, joint_num, center)
    if mask:
        graph.remove_geometry(gtem)
    gtem, mask, chain = get_box_diplay(ghnd, "init_{}".format(idx), cell_dat, N_BEGIN_INIT, joint_num, center, color=(0,0,0,0.8))
    if mask:
        graph.remove_geometry(gtem)
    gtem, mask, chain = get_box_diplay(ghnd, "goal_{}".format(idx), cell_dat, N_BEGIN_GOAL, joint_num, center, color=(0,0,0,0.8))
    if mask:
        graph.remove_geometry(gtem)

## show twist

In [ ]:
centers = get_centers(Nwdh, L_CELL)
for idx, center, cell_dat in zip(range(Nwdh[0]*Nwdh[1]*Nwdh[2]), centers.reshape((-1,3)), scene_data.reshape((-1, scene_data.shape[-1]))):
#     gtem, mask, chain = get_box_diplay(ghnd, "box_{}".format(idx), cell_dat, 0, joint_num, center)
#     gtem, mask, chain = get_cyl_diplay(ghnd, "cyl_{}".format(idx), cell_dat, N_BEGIN_CYL, joint_num, center)
    gtem, mask, chain = get_box_diplay(ghnd, "init_{}".format(idx), cell_dat, N_BEGIN_INIT, joint_num, center, color=(0,0,0,0.8))
#     gtem, mask, chain = get_box_diplay(ghnd, "goal_{}".format(idx), cell_dat, N_BEGIN_GOAL, joint_num, center, color=(0.8,0.8,0.8,0.8))
    if mask:
        if np.max(chain)>0:
            graph.add_marker(gtem)
            break
    graph.remove_geometry(gtem)
ptem, vtem, atem, btem = get_twist_tems(ghnd, cell_dat, center, chain, 2, joint_num, L_CELL)
graph.add_marker(ptem)
graph.add_marker(vtem)
graph.add_marker(atem)
graph.add_marker(btem)

# remove twist

In [ ]:
graph.remove_geometry(ptem)
graph.remove_geometry(atem)
graph.remove_geometry(vtem)
graph.remove_geometry(btem)

In [179]:
graph.remove_geometry(btem)