## Check List 3.1 - MultiICP Detector
* **3.1.1 MultiICP**  
  - initialize, set_config, get_config, get_image, detect, detect_and_register, disconnect  
  
  
* **TBD**
  - Auto initialization to estimate initial guess for ICP is not perfect
  - Robust and reliable initial guess for gloabl registration will be done
  - Multiple instance for the same class will be done

## Set running directory to Project source

In [1]:
import os
import sys
import numpy as np
import cv2
import copy
import matplotlib.pyplot as plt
os.chdir(os.path.join(os.environ["RNB_PLANNING_DIR"], 'src'))

In [2]:
from pkg.global_config import RNB_PLANNING_DIR
from pkg.utils.utils import *    
from pkg.utils.rotation_utils import *
from pkg.controller.combined_robot import *
from pkg.geometry.builder.scene_builder import SceneBuilder
from pkg.geometry.geometry import GeometryItem
from pkg.geometry.geotype import GEOTYPE
from pkg.detector.detector_interface import DetectionLevel
from pkg.detector.multiICP.config import *

In [3]:
# add camera geometry
def add_cam(gscene, tool_link="indy0_tcp"):
    gscene.create_safe(gtype=GEOTYPE.CYLINDER, name="cam", link_name=tool_link,
                       dims=(0.061, 0.061, 0.026), center=(-0.0785, 0, 0.013), rpy=(0, 0, 0),
                       color=(0.8, 0.8, 0.8, 0.5), display=True, fixed=True, collision=False)

    gscene.create_safe(gtype=GEOTYPE.CYLINDER, name="cam_col", link_name=tool_link,
                       dims=(0.081, 0.081, 0.046), center=(-0.0785, 0, 0.013), rpy=(0, 0, 0),
                       color=(0.8, 0.8, 0.8, 0.2), display=True, fixed=True, collision=True)

    viewpoint = gscene.create_safe(gtype=GEOTYPE.SPHERE, name="viewpoint", link_name=tool_link,
                                   dims=(0.01, 0.01, 0.01), center=(-0.013, 0, 0), rpy=(0, 0, -np.pi / 2),
                                   color=(1, 0, 0, 0.3), display=True, fixed=True, collision=False, parent="cam")

    gscene.create_safe(gtype=GEOTYPE.CYLINDER, name="body", link_name=tool_link,
                       dims=(0.067, 0.067, 0.0335), center=(-0.0785, 0, -0.01675), rpy=(0, 0, 0),
                       color=(0.8, 0.8, 0.8, 1), display=True, fixed=True, collision=False)

    gscene.create_safe(gtype=GEOTYPE.CYLINDER, name="body_col", link_name=tool_link,
                       dims=(0.087, 0.087, 0.0535), center=(-0.0785, 0, -0.01675), rpy=(0, 0, 0),
                       color=(0.8, 0.8, 0.8, 0.2), display=True, fixed=True, collision=True)

    gscene.create_safe(gtype=GEOTYPE.SPHERE, name="backhead", link_name=tool_link,
                       dims=(0.067, 0.067, 0.067), center=(-0.0785, 0, -0.0335), rpy=(0, 0, 0),
                       color=(0.8, 0.8, 0.8, 1), display=True, fixed=True, collision=False)

    gscene.create_safe(gtype=GEOTYPE.SPHERE, name="backhead_col", link_name=tool_link,
                       dims=(0.087, 0.087, 0.087), center=(-0.0785, 0, -0.0335), rpy=(0, 0, 0),
                       color=(0.8, 0.8, 0.8, 0.2), display=True, fixed=True, collision=True)
    return viewpoint

### 3.1.1 MultiICP

In [4]:
from pkg.detector.multiICP.multiICP import MultiICP, MultiICP_Obj
from pkg.detector.camera.realsense import RealSense
from pkg.detector.detector_interface import DetectionLevel

##### create multiICP instance

In [5]:
micp = MultiICP(None)

##### initialize()

In [6]:
config_list, img_dim = load_pickle(RNB_PLANNING_DIR+"release/multiICP_data/cam_configs.pkl")
micp.initialize(config_list=config_list, img_dim=img_dim)

Camera is not set - skip initialization, use manually given camera configs


##### create SceneBuilder instance and geometry scene

In [7]:
INDY_BASE_OFFSET = (0.172,0,0.439)
INDY_BASE_RPY = (0,0,0)
mobile_config = RobotConfig(0, RobotType.kmb, ((0,0,0), (0,0,0)),
                "{}/{}".format(None, None))
robot_config = RobotConfig(1, RobotType.indy7, 
                           (INDY_BASE_OFFSET, INDY_BASE_RPY),
                           None, root_on="kmb0_platform", 
                           specs={"no_sdk":True})
MOBILE_NAME = mobile_config.get_indexed_name()
ROBOT_NAME = robot_config.get_indexed_name()
crob = CombinedRobot(robots_on_scene=[mobile_config, robot_config]
              , connection_list=[False, False])

scene_builder = SceneBuilder.instance(detector=micp)
gscene = scene_builder.create_gscene(crob)

from pkg.planning.scene import PlanningScene
pscene = PlanningScene(gscene, combined_robot=crob)

ROBOT_BASE = pscene.robot_chain_dict[ROBOT_NAME]['link_names'][0]
TIP_LINK = pscene.robot_chain_dict[ROBOT_NAME]["tip_link"]
MOBILE_BASE = pscene.robot_chain_dict[MOBILE_NAME]["tip_link"]
HOLD_LINK = MOBILE_BASE

viewpoint = add_cam(gscene, tool_link=TIP_LINK)
VIEW_POSE = np.deg2rad([  0., 50.,  -70.,  -0.,  -90., 0])
VIEW_LOC = [0]*6
VIEW_POSE_EXT = np.array(VIEW_LOC + list(VIEW_POSE))
T_bc = viewpoint.get_tf(VIEW_POSE_EXT)
T_cb = SE3_inv(T_bc)
gscene.show_pose(VIEW_POSE_EXT)

connection command:
kmb0: False
indy1: False
Please create a subscriber to the marker
publication OK
published: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Please create a subscriber to the marker


### Set MultiICP configs
* You have to make micp, hrule and grule for each object you want to detect

* hrule means heuristic rule for special object which cannot be detected thorugh mask rcnn using COCO dataset

* grule means initial guess(R,t) for ICP

* Run shraed detector to detect object in color image

##### Run shared detector for object detection on bash
```bash
python3 $RNB_PLANNING_DIR/src/pkg/detector/multiICP/shared_detector.py --dims='(720,1280,3)'
```
* change dims=(*) depending on your camera resolution

#### Clearing shared detector channels if zombie memory remains
```python
from pkg.utils.shared_function import clear_channels_on, sa
clear_channels_on("SharedDetector")
```

In [8]:
from pkg.utils.shared_function import clear_channels_on, sa
clear_channels_on("SharedDetector")

from pkg.detector.multiICP.shared_detector import SharedDetectorGen
sd = SharedDetectorGen(micp.img_dim+(3,))()
sd.init()

##### Load example data (for bed, closet)
* You need to prepare example data and stl model to test MultiICP detector 
* Use color image, depth image and csv file which has joint values Q with cam_intrins, depth_scale 
* file path: release/multiICP_data/

In [9]:
def load_rdict(file_name):
    rdict = {}
    
    rdict['color'] = cv2.imread(
        os.path.join(RNB_PLANNING_DIR, 'release/multiICP_data/', file_name + '.jpg'), flags=cv2.IMREAD_UNCHANGED)
    rdict['depth'] = cv2.imread(
        os.path.join(RNB_PLANNING_DIR, 'release/multiICP_data/', file_name + '.png'), flags=cv2.IMREAD_UNCHANGED)
    
    Q = np.loadtxt(os.path.join(RNB_PLANNING_DIR, 'release/multiICP_data/', file_name + '.csvd'), delimiter=",")
    return rdict, np.array(Q)

rdict, Qtest = load_rdict("test_1")
color_img = rdict['color']
depth_img = rdict['depth']
Tc = viewpoint.get_tf(Qtest)
gscene.show_pose(Qtest)

obj_info_dict = get_obj_info()

In [10]:
# object items you want to detect
# heuristic rule items, Initial guess rule items
micp_bed = MultiICP_Obj(obj_info_dict["bed"], None,
                        OffsetOnModelCoord("bed", R=np.matmul(T_cb[:3, :3], Rot_axis(3, np.pi)),
                                          offset=np.matmul(T_cb[:3, :3], (1.1 * 0.5, 0, -0.5))))

mrule_closet = MaskBoxRule("closet", "bed", merge_rule=np.all)
mrule_closet.update_rule = ClosetRuleFun(mrule_closet)
micp_closet = MultiICP_Obj(obj_info_dict["closet"], 
                           mrule_closet,
                           OffsetOnModelCoord("closet", 
                                             offset=(0, 1, 0.3),
                                             use_median=True
                                     ))

In [11]:
micp_dict = {"bed": micp_bed, "closet": micp_closet}

In [12]:
micp.set_config(micp_dict, sd, crob, viewpoint)

##### detect()
* Object Detection through swin-transformer based mask rcnn using mmdet
* To use test data(color, depth image and joint value Q), you have to call cache_sensor()
* Detection result is the transformation w.r.t base coord

In [13]:
micp.cache_sensor(color_img, depth_img, Qtest)

In [14]:
pose_dict = micp.detect(visualize=True)

name_mask is None
===== Detected : handbag, 1 object(s) =====
===== Detected : suitcase, 1 object(s) =====
===== Detected : bowl, 3 object(s) =====
===== Detected : bed, 1 object(s) =====
===== Detected : clock, 1 object(s) =====

'bed' is not in gscene. Use manual input for initial guess

Apply point-to-point ICP
registration::RegistrationResult with fitness=8.427715e-01, inlier_rmse=6.878896e-02, and correspondence_set size of 5060
Access transformation to get result.
Transformation is:
[[ 0.82151496 -0.10241734  0.56091342 -0.5930757 ]
 [-0.22373454 -0.9627413   0.15189486  0.65864584]
 [ 0.52445784 -0.2502796  -0.81382068  4.62658037]
 [ 0.          0.          0.          1.        ]]
Apply point-to-point ICP
registration::RegistrationResult with fitness=8.477495e-01, inlier_rmse=4.377588e-02, and correspondence_set size of 2166
Access transformation to get result.
Transformation is:
[[ 0.82315056 -0.06585229  0.5639917  -0.57596027]
 [-0.15879798 -0.98031779  0.11730398  0.723657

##### reset_reference_coord()
* **WARNING** MultiICP need pre-initialized CombinedRobot and GeometryScene: Should not call reset_reference_coord

##### detect_and_register()
* Detect items in the field of view and register them to the GeometryScene
* They will appear in the RVIZ



In [16]:
micp.cache_sensor(color_img, depth_img, Qtest)

In [17]:
gtem_dict = scene_builder.detect_and_register(level_mask=[DetectionLevel.ENVIRONMENT])
# gtem_dict = scene_builder.detect_and_register(level_mask=[DetectionLevel.MOVABLE])

name_mask is ['closet', 'bed']
===== Detected : bed, 1 object(s) =====

'bed' is not in gscene. Use manual input for initial guess

Apply point-to-point ICP
registration::RegistrationResult with fitness=8.372751e-01, inlier_rmse=6.896300e-02, and correspondence_set size of 5027
Access transformation to get result.
Transformation is:
[[ 0.82322285 -0.09780685  0.55922979 -0.58576874]
 [-0.21700862 -0.96445587  0.15077177  0.66013347]
 [ 0.52460595 -0.24547645 -0.81518704  4.62138416]
 [ 0.          0.          0.          1.        ]]
Apply point-to-point ICP
registration::RegistrationResult with fitness=8.428627e-01, inlier_rmse=4.210993e-02, and correspondence_set size of 2167
Access transformation to get result.
Transformation is:
[[ 0.82555468 -0.05574983  0.5615616  -0.57364343]
 [-0.15049297 -0.98082034  0.12386818  0.71511024]
 [ 0.54388541 -0.18677103 -0.81811078  4.61797162]
 [ 0.          0.          0.          1.        ]]
Found 6DoF pose of bed
===== Apply heuristic rule fo

##### disconnect()

In [19]:
micp.disconnect()